apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "podinfo.fullname" . }}-config
  labels:
    {{- include "podinfo.labels" . | nindent 4 }}
data:
  PODINFO_UI_COLOR: {{ .Values.config.uiColor | quote }}